### ISSUE TITLE
dockerignore may be wrong...

### ISSUE THREAD

**Issue by cicorias** [michaelperel/putput#40]
when building if i have a `venv` local the docker build sends 35 mb to the docker host.  It has to duplicate what's in `.gitignore` and not just include the one line of `.gitignore`.

![image](https://user-images.githubusercontent.com/1080406/51289956-1dbac600-19b7-11e9-8a90-56ba926c6ce2.png)

**Comment by michaelperel** [comment]
Currently, the .dockerignore is ignoring the .gitignore, but not the contents that are in the .gitignore
