### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by michaelperel** [michaelperel/putput#6]
* Publish to PyPI (already reserved the name), so it is pip installable
* Only publish the second putput folder (do not publish the samples as part of the package)

**Comment by c-w** [comment]
I'd recommend to use the PyPI deploy on Travis for this which can be configured to publish a new package whenever a new release is created on Github.

Here are a couple of sample Travis config files that show how to use this approach:
- [c-w/gutenberg](https://github.com/c-w/gutenberg/blob/a79dbd78ecc27addbf70063b0a6750ebabb33890/.travis.yml#L32-L40)
- [ascoderu/pyzmail](https://github.com/ascoderu/pyzmail/blob/7e81342d39a9fae50dd40f1c1b098b510569fcb2/.travis.yml#L18-L30)
- [ascoderu/xtarfile](https://github.com/ascoderu/xtarfile/blob/18f54e7c1096bebf1e5dfd04194fdfa6004c743a/.travis.yml#L16-L28).

You can use the [Travis CLI](https://github.com/travis-ci/travis.rb#command-line-client) to encrypt your PyPI password and add it to the config file. The CLI takes a little while to install but there's also an unofficial [Dockerized Travis CLI](https://hub.docker.com/r/skandyla/travis-cli/).
