### ISSUE TITLE
Add Grouping Functionality

### ISSUE THREAD

**Issue by armanrahman22** [michaelperel/putput#65]
- [x] add the ability to define groupings (e.g. "Change the chicken to a burder" -> [Substitite, (chicken, burger)]) either via hooks or part of the pattern definition syntax

After working on it...
- [x] add syntax to the pattern definition file to specify groups
- [x] add the equivalent of token handlers, but make them group handlers
- [x] add rules for the new syntax into the validator
- [ ] refactor tests / add tests

**Comment by michaelperel** [comment]
One thought we have to implement this is to give token handlers the context of where the token is in an utterance as well as access to the tokens of the entire utterance

**Comment by armanrahman22** [comment]
Exploring adding grouping functionality as part of the pattern definition syntax with base_groups (similar to base_tokens)
